### ISSUE TITLE
Error running tests in Firefox on ubuntu-latest via GH Actions

### ISSUE THREAD

**Issue by alexgibson** [jasmine/jasmine-browser-runner#56]
I'm hitting what I believe is this issue https://github.com/SeleniumHQ/selenium/issues/13169 when trying to run jasmine-browser-runner via GitHub Actions on Ubuntu >= 22.0.4. From my understanding, it is due to Firefox snap being the new default on Ubuntu, but it is installed in a different location.

```
Jasmine server is running here: http://localhost:9876
Jasmine tests are here:         /home/runner/work/dnt-helper/dnt-helper/tests/dist
Source files are here:          /home/runner/work/dnt-helper/dnt-helper/tests/dist
Running tests in the browser...
InvalidArgumentError: binary is not a Firefox executable
    at Object.throwDecodedError (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/error.js:521:15)
    at parseHttpResponse (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/http.js:514:13)
    at Executor.execute (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/http.js:446:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: ''
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
InvalidArgumentError: binary is not a Firefox executable
    at Object.throwDecodedError (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/error.js:521:15)
    at parseHttpResponse (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/http.js:514:13)
    at Executor.execute (/home/runner/work/dnt-helper/dnt-helper/node_modules/selenium-webdriver/lib/http.js:446:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: ''
}
```

This is a basic GitHub action template that can reproduce the issue:

```
name: "CI"
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Install framebuffer (xvfb), Firefox and Chromium"
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser firefox xvfb
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install JS dependencies"
        run: npm ci
      - name: "Run JS tests"
        run: xvfb-run npm test
```

From the issue I linked to it does not look like this is something Selenium will fix, since it supports passing alternate paths to the driver/executable already. However given that, I'm not quite sure how I can tell jasmine-browser-runner to instruct Selenium to use a different browser/driver path?
